version: '3'

services:
  travel-users-service:
    container_name: travel-users-service
    image: node:20
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.travel-users-service.rule=PathPrefix(`/api/v1/users`)"
      - "traefik.http.routers.travel-users-service.entrypoints=web"
    volumes:
      - .:/usr/src/app
      - ./../travel-sdk:/usr/src/travel-sdk
    ports:
      - 3000:3000
    working_dir: /usr/src/app
    command: npm run start:debug
    depends_on:
      - travel-users-db
    networks:
      - travel-network

  travel-users-db:
    container_name: travel-users-db
    image: mariadb:11
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: travel_db
    networks:
      - travel-network

networks:
  travel-network:
    external: true
    name: travel-network
